/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface Country {
  countryCode: string;
  countryName: string;
  currency: string;
  pricingCurrency?: string;
}

export interface CurrencySymbolMapFn {[currencySymbol: string]: string};

export const currencySymbolMap: CurrencySymbolMapFn = {
  'USD': 'USD',
  'EGP': 'EGP',
  'TZS': 'TZS',
  'AED': 'AED',
  'QAR': 'QAR',
  'SAR': 'SAR',
  'HUF': 'HUF',
  'R$': 'BRL',
  'CN¥': 'CNY',
  'HK$': 'HKD',
  'S$': 'SGD',
  'MX$': 'MXN',
  'NT$': 'TWD',
  'CLP$': 'CLP',
  'COL$': 'COP',
  'S/': 'PEN',
  'Rp': 'IDR',
  'Ft': 'HUF',
  'Kč': 'CZK',
  'zł': 'PLN',
  'лв': 'BGN',
  'ден': 'MKD',
  'lei': 'RON',
  '€': 'EUR',
  '£': 'GBP',
  '¥': 'JPY',
  '₩': 'KRW',
  '₹': 'INR',
  '₽': 'RUB',
  '₪': 'ILS',
  '₺': 'TRY',
  '₴': 'UAH',
  '₸': 'KZT',
  'R': 'ZAR',
  'RM': 'MYR',
  '₱': 'PHP',
  '฿': 'THB',
  '₫': 'VND',
  '₦': 'NGN',
  'Rs': 'PKR'
};

export const countryData: Country[] = [
  { countryCode: 'dz', countryName: 'Algeria', currency: 'DZD', pricingCurrency: 'USD' },
  { countryCode: 'ao', countryName: 'Angola', currency: 'AOA', pricingCurrency: 'USD' },
  { countryCode: 'ai', countryName: 'Anguilla', currency: 'XCD', pricingCurrency: 'USD' },
  { countryCode: 'ag', countryName: 'Antigua and Barbuda', currency: 'XCD', pricingCurrency: 'USD' },
  { countryCode: 'ar', countryName: 'Argentina', currency: 'ARS' },
  { countryCode: 'am', countryName: 'Armenia', currency: 'AMD' },
  { countryCode: 'au', countryName: 'Australia', currency: 'AUD' },
  { countryCode: 'at', countryName: 'Austria', currency: 'EUR' },
  { countryCode: 'az', countryName: 'Azerbaijan', currency: 'AZN' },
  { countryCode: 'bs', countryName: 'Bahamas', currency: 'BSD', pricingCurrency: 'USD' },
  { countryCode: 'bh', countryName: 'Bahrain', currency: 'BHD', pricingCurrency: 'USD' },
  { countryCode: 'bb', countryName: 'Barbados', currency: 'BBD', pricingCurrency: 'USD' },
  { countryCode: 'by', countryName: 'Belarus', currency: 'BYN' },
  { countryCode: 'be', countryName: 'Belgium', currency: 'EUR' },
  { countryCode: 'bz', countryName: 'Belize', currency: 'BZD', pricingCurrency: 'USD' },
  { countryCode: 'bm', countryName: 'Bermuda', currency: 'BMD', pricingCurrency: 'USD' },
  { countryCode: 'bt', countryName: 'Bhutan', currency: 'BTN', pricingCurrency: 'USD' },
  { countryCode: 'bo', countryName: 'Bolivia', currency: 'BOB' },
  { countryCode: 'bw', countryName: 'Botswana', currency: 'BWP', pricingCurrency: 'USD' },
  { countryCode: 'br', countryName: 'Brazil', currency: 'BRL' },
  { countryCode: 'vg', countryName: 'British Virgin Islands', currency: 'USD' },
  { countryCode: 'bn', countryName: 'Brunei Darussalam', currency: 'BND', pricingCurrency: 'USD' },
  { countryCode: 'bg', countryName: 'Bulgaria', currency: 'BGN' },
  { countryCode: 'kh', countryName: 'Cambodia', currency: 'KHR' },
  { countryCode: 'ca', countryName: 'Canada', currency: 'CAD' },
  { countryCode: 'cv', countryName: 'Cape Verde', currency: 'CVE' },
  { countryCode: 'ky', countryName: 'Cayman Islands', currency: 'KYD' },
  { countryCode: 'cl', countryName: 'Chile', currency: 'CLP' },
  { countryCode: 'cn', countryName: 'China', currency: 'CNY', pricingCurrency: 'CNY ' },
  { countryCode: 'co', countryName: 'Colombia', currency: 'COP' },
  { countryCode: 'cr', countryName: 'Costa Rica', currency: 'CRC' },
  { countryCode: 'hr', countryName: 'Croatia', currency: 'EUR' },
  { countryCode: 'cy', countryName: 'Cyprus', currency: 'EUR' },
  { countryCode: 'cz', countryName: 'Czech Republic', currency: 'CZK' },
  { countryCode: 'dk', countryName: 'Denmark', currency: 'DKK' },
  { countryCode: 'dm', countryName: 'Dominica', currency: 'XCD', pricingCurrency: 'USD' },
  { countryCode: 'do', countryName: 'Dominican Republic', currency: 'DOP' },
  { countryCode: 'ec', countryName: 'Ecuador', currency: 'USD' },
  { countryCode: 'eg', countryName: 'Egypt', currency: 'EGP' },
  { countryCode: 'sv', countryName: 'El Salvador', currency: 'USD' },
  { countryCode: 'ee', countryName: 'Estonia', currency: 'EUR' },
  { countryCode: 'sz', countryName: 'Eswatini', currency: 'SZL', pricingCurrency: 'USD' },
  { countryCode: 'fj', countryName: 'Fiji', currency: 'FJD', pricingCurrency: 'USD' },
  { countryCode: 'fi', countryName: 'Finland', currency: 'EUR' },
  { countryCode: 'fr', countryName: 'France', currency: 'EUR' },
  { countryCode: 'gm', countryName: 'Gambia', currency: 'GMD', pricingCurrency: 'USD' },
  { countryCode: 'ge', countryName: 'Georgia', currency: 'GEL' },
  { countryCode: 'de', countryName: 'Germany', currency: 'EUR' },
  { countryCode: 'gh', countryName: 'Ghana', currency: 'GHS' },
  { countryCode: 'gr', countryName: 'Greece', currency: 'EUR' },
  { countryCode: 'gd', countryName: 'Grenada', currency: 'XCD', pricingCurrency: 'USD' },
  { countryCode: 'gt', countryName: 'Guatemala', currency: 'GTQ' },
  { countryCode: 'gy', countryName: 'Guyana', currency: 'GYD', pricingCurrency: 'USD' },
  { countryCode: 'hn', countryName: 'Honduras', currency: 'HNL' },
  { countryCode: 'hk', countryName: 'Hong Kong', currency: 'HKD' },
  { countryCode: 'hu', countryName: 'Hungary', currency: 'HUF' },
  { countryCode: 'is', countryName: 'Iceland', currency: 'ISK' },
  { countryCode: 'in', countryName: 'India', currency: 'INR' },
  { countryCode: 'id', countryName: 'Indonesia', currency: 'IDR' },
  { countryCode: 'ie', countryName: 'Ireland', currency: 'EUR' },
  { countryCode: 'il', countryName: 'Israel', currency: 'ILS' },
  { countryCode: 'it', countryName: 'Italy', currency: 'EUR' },
  { countryCode: 'jm', countryName: 'Jamaica', currency: 'JMD' },
  { countryCode: 'jp', countryName: 'Japan', currency: 'JPY' },
  { countryCode: 'jo', countryName: 'Jordan', currency: 'JOD', pricingCurrency: 'USD' },
  { countryCode: 'kz', countryName: 'Kazakhstan', currency: 'KZT' },
  { countryCode: 'ke', countryName: 'Kenya', currency: 'KES' },
  { countryCode: 'kr', countryName: 'Korea, Republic of', currency: 'KRW' },
  { countryCode: 'kw', countryName: 'Kuwait', currency: 'KWD', pricingCurrency: 'USD' },
  { countryCode: 'kg', countryName: 'Kyrgyzstan', currency: 'KGS' },
  { countryCode: 'la', countryName: 'Lao People\'s Democratic Republic', currency: 'LAK' },
  { countryCode: 'lv', countryName: 'Latvia', currency: 'EUR' },
  { countryCode: 'lb', countryName: 'Lebanon', currency: 'LBP', pricingCurrency: 'USD' },
  { countryCode: 'lr', countryName: 'Liberia', currency: 'LRD', pricingCurrency: 'USD' },
  { countryCode: 'lt', countryName: 'Lithuania', currency: 'EUR' },
  { countryCode: 'lu', countryName: 'Luxembourg', currency: 'EUR' },
  { countryCode: 'mo', countryName: 'Macao', currency: 'MOP' },
  { countryCode: 'mg', countryName: 'Madagascar', currency: 'MGA', pricingCurrency: 'USD' },
  { countryCode: 'mw', countryName: 'Malawi', currency: 'MWK', pricingCurrency: 'USD' },
  { countryCode: 'my', countryName: 'Malaysia', currency: 'MYR' },
  { countryCode: 'mv', countryName: 'Maldives', currency: 'MVR' },
  { countryCode: 'ml', countryName: 'Mali', currency: 'XOF' },
  { countryCode: 'mt', countryName: 'Malta', currency: 'EUR' },
  { countryCode: 'mr', countryName: 'Mauritania', currency: 'MRU', pricingCurrency: 'USD'  },
  { countryCode: 'mu', countryName: 'Mauritius', currency: 'MUR' },
  { countryCode: 'mx', countryName: 'Mexico', currency: 'MXN' },
  { countryCode: 'fm', countryName: 'Micronesia, Federated States of', currency: 'USD' },
  { countryCode: 'md', countryName: 'Moldova, Republic of', currency: 'MDL' },
  { countryCode: 'mn', countryName: 'Mongolia', currency: 'MNT', pricingCurrency: 'USD' },
  { countryCode: 'ms', countryName: 'Montserrat', currency: 'XCD', pricingCurrency: 'USD' },
  { countryCode: 'mz', countryName: 'Mozambique', currency: 'MZN' },
  { countryCode: 'mm', countryName: 'Myanmar', currency: 'MMK' },
  { countryCode: 'na', countryName: 'Namibia', currency: 'NAD' },
  { countryCode: 'np', countryName: 'Nepal', currency: 'NPR' },
  { countryCode: 'nl', countryName: 'Netherlands', currency: 'EUR' },
  { countryCode: 'nz', countryName: 'New Zealand', currency: 'NZD' },
  { countryCode: 'ni', countryName: 'Nicaragua', currency: 'NIO' },
  { countryCode: 'ne', countryName: 'Niger', currency: 'XOF', pricingCurrency: 'USD' },
  { countryCode: 'ng', countryName: 'Nigeria', currency: 'NGN' },
  { countryCode: 'mk', countryName: 'North Macedonia', currency: 'MKD', pricingCurrency: 'USD' },
  { countryCode: 'no', countryName: 'Norway', currency: 'NOK' },
  { countryCode: 'om', countryName: 'Oman', currency: 'OMR', pricingCurrency: 'USD' },
  { countryCode: 'pk', countryName: 'Pakistan', currency: 'PKR' },
  { countryCode: 'pw', countryName: 'Palau', currency: 'USD' },
  { countryCode: 'pa', countryName: 'Panama', currency: 'PAB' },
  { countryCode: 'pg', countryName: 'Papua New Guinea', currency: 'PGK', pricingCurrency: 'USD' },
  { countryCode: 'py', countryName: 'Paraguay', currency: 'PYG' },
  { countryCode: 'pe', countryName: 'Peru', currency: 'PEN' },
  { countryCode: 'ph', countryName: 'Philippines', currency: 'PHP' },
  { countryCode: 'pl', countryName: 'Poland', currency: 'PLN' },
  { countryCode: 'pt', countryName: 'Portugal', currency: 'EUR' },
  { countryCode: 'qa', countryName: 'Qatar', currency: 'QAR' },
  { countryCode: 'ro', countryName: 'Romania', currency: 'RON' },
  { countryCode: 'ru', countryName: 'Russia', currency: 'RUB' },
  { countryCode: 'sa', countryName: 'Saudi Arabia', currency: 'SAR' },
  { countryCode: 'sn', countryName: 'Senegal', currency: 'XOF' },
  { countryCode: 'sc', countryName: 'Seychelles', currency: 'SCR' },
  { countryCode: 'sl', countryName: 'Sierra Leone', currency: 'SLL', pricingCurrency: 'USD' },
  { countryCode: 'sg', countryName: 'Singapore', currency: 'SGD' },
  { countryCode: 'sk', countryName: 'Slovakia', currency: 'EUR' },
  { countryCode: 'si', countryName: 'Slovenia', currency: 'EUR' },
  { countryCode: 'sb', countryName: 'Solomon Islands', currency: 'SBD', pricingCurrency: 'USD' },
  { countryCode: 'za', countryName: 'South Africa', currency: 'ZAR' },
  { countryCode: 'es', countryName: 'Spain', currency: 'EUR' },
  { countryCode: 'lk', countryName: 'Sri Lanka', currency: 'LKR' },
  { countryCode: 'kn', countryName: 'St. Kitts and Nevis', currency: 'XCD', pricingCurrency: 'USD' },
  { countryCode: 'lc', countryName: 'St. Lucia', currency: 'XCD', pricingCurrency: 'USD' },
  { countryCode: 'vc', countryName: 'St. Vincent and The Grenadines', currency: 'XCD', pricingCurrency: 'USD' },
  { countryCode: 'sr', countryName: 'Suriname', currency: 'SRD', pricingCurrency: 'USD' },
  { countryCode: 'se', countryName: 'Sweden', currency: 'SEK' },
  { countryCode: 'ch', countryName: 'Switzerland', currency: 'CHF' },
  { countryCode: 'tw', countryName: 'Taiwan', currency: 'TWD' },
  { countryCode: 'tj', countryName: 'Tajikistan', currency: 'TJS' },
  { countryCode: 'tz', countryName: 'Tanzania, United Republic of', currency: 'TZS' },
  { countryCode: 'th', countryName: 'Thailand', currency: 'THB' },
  { countryCode: 'tt', countryName: 'Trinidad and Tobago', currency: 'TTD' },
  { countryCode: 'tn', countryName: 'Tunisia', currency: 'TND', pricingCurrency: 'USD' },
  { countryCode: 'tr', countryName: 'Turkey', currency: 'TRY' },
  { countryCode: 'tm', countryName: 'Turkmenistan', currency: 'TMT' },
  { countryCode: 'tc', countryName: 'Turks and Caicos', currency: 'USD' },
  { countryCode: 'ug', countryName: 'Uganda', currency: 'UGX', pricingCurrency: 'USD' },
  { countryCode: 'ua', countryName: 'Ukraine', currency: 'UAH' },
  { countryCode: 'ae', countryName: 'United Arab Emirates', currency: 'AED' },
  { countryCode: 'gb', countryName: 'United Kingdom', currency: 'GBP' },
  { countryCode: 'us', countryName: 'United States', currency: 'USD' },
  { countryCode: 'uy', countryName: 'Uruguay', currency: 'UYU' },
  { countryCode: 'uz', countryName: 'Uzbekistan', currency: 'UZS', pricingCurrency: 'USD' },
  { countryCode: 've', countryName: 'Venezuela', currency: 'VES' },
  { countryCode: 'vn', countryName: 'Vietnam', currency: 'VND' },
  { countryCode: 'ye', countryName: 'Yemen', currency: 'YER', pricingCurrency: 'USD' },
  { countryCode: 'zw', countryName: 'Zimbabwe', currency: 'ZWL' },
];
