/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/** A dictionary mapping two-letter country codes to their Apple store currency code. */
export const apple_store_currency_map: { [key: string]: string } = {
    // Americas (mostly USD region)
    'us': 'USD', 'pr': 'USD', 'vi': 'USD', 'as': 'USD', 'um': 'USD', 'tc': 'USD',
    'vg': 'USD', 'io': 'USD', 'gs': 'USD', 'cw': 'USD', 'sx': 'USD', 'bq': 'USD', 'mf': 'USD',

    // Eurozone countries
    'at': 'EUR', 'be': 'EUR', 'cy': 'EUR', 'ee': 'EUR', 'fi': 'EUR', 'fr': 'EUR', 'de': 'EUR',
    'gr': 'EUR', 'ie': 'EUR', 'it': 'EUR', 'lv': 'EUR', 'lt': 'EUR', 'lu': 'EUR', 'mt': 'EUR',
    'nl': 'EUR', 'pt': 'EUR', 'sk': 'EUR', 'si': 'EUR', 'es': 'EUR', 'hr': 'EUR',
    'me': 'EUR', 'rs': 'EUR',

    // Other countries using local currencies
    'au': 'AUD',
    'bg': 'BGN',
    'br': 'BRL',
    'ca': 'CAD',
    'cl': 'CLP',
    'cn': 'CNY',
    'co': 'COP',
    'cr': 'CRC',
    'cz': 'CZK',
    'dk': 'DKK',
    'eg': 'EGP',
    'hk': 'HKD',
    'hu': 'HUF',
    'in': 'INR',
    'id': 'IDR',
    'il': 'ILS',
    'jp': 'JPY',
    'kz': 'KZT',
    'kr': 'KRW',
    'my': 'MYR',
    'mx': 'MXN',
    'nz': 'NZD',
    'no': 'NOK',
    'ph': 'PHP',
    'pl': 'PLN',
    'qa': 'QAR',
    'ro': 'RON',
    'ru': 'RUB',
    'sa': 'SAR',
    'sg': 'SGD',
    'se': 'SEK',
    'ch': 'CHF',
    'tw': 'TWD',
    'th': 'THB',
    'tr': 'TRY',
    'ae': 'AED',
    'gb': 'GBP',
    'vn': 'VND',
    'ng': 'NGN',
    'pk': 'PKR',
    'za': 'ZAR',
    'tz': 'TZS',

    // Middle East exceptions using USD
    'om': 'USD', 'ps': 'USD', 'kw': 'USD', 'bh': 'USD',

    // Smaller and Rest of World with USD stores
    'af': 'USD', 'al': 'USD', 'dz': 'USD', 'ao': 'USD', 'aq': 'USD', 'ar': 'USD',
    'am': 'USD', 'aw': 'USD', 'az': 'USD', 'bs': 'USD', 'bd': 'USD', 'bb': 'USD',
    'by': 'USD', 'bz': 'USD', 'bj': 'USD', 'bt': 'USD', 'bo': 'USD', 'ba': 'USD',
    'bw': 'USD', 'bn': 'USD', 'bf': 'USD', 'bi': 'USD', 'kh': 'USD', 'cm': 'USD',
    'cv': 'USD', 'ky': 'USD', 'cf': 'USD', 'td': 'USD', 'km': 'USD', 'cg': 'USD',
    'cd': 'USD', 'dj': 'USD', 'dm': 'USD', 'do': 'USD', 'ec': 'USD', 'sv': 'USD',
    'gq': 'USD', 'er': 'USD', 'et': 'USD', 'fj': 'USD', 'ga': 'USD', 'gm': 'USD',
    'ge': 'USD', 'gh': 'USD', 'gd': 'USD', 'gt': 'USD', 'gn': 'USD', 'gw': 'USD',
    'gy': 'USD', 'ht': 'USD', 'hn': 'USD', 'is': 'USD', 'jm': 'USD', 'jo': 'USD',
    'ke': 'USD', 'ki': 'USD', 'kp': 'USD', 'kg': 'USD', 'la': 'USD', 'lb': 'USD',
    'ls': 'USD', 'lr': 'USD', 'ly': 'USD', 'mg': 'USD', 'mw': 'USD', 'mv': 'USD',
    'ml': 'USD', 'mh': 'USD', 'mr': 'USD', 'mu': 'USD', 'fm': 'USD', 'md': 'USD',
    'mc': 'USD', 'mn': 'USD', 'ms': 'USD', 'ma': 'USD', 'zw': 'USD', 'xk': 'USD',
    'mz': 'USD', 'mm': 'USD', 'na': 'USD', 'nr': 'USD', 'np': 'USD', 'ni': 'USD',
    'ne': 'USD', 'nu': 'USD', 'nf': 'USD', 'mk': 'USD', 'zm': 'USD', 'iq': 'USD',
    'pw': 'USD', 'pa': 'USD', 'pg': 'USD', 'py': 'USD', 're': 'USD', 'rw': 'USD',
    'kn': 'USD', 'lc': 'USD', 'vc': 'USD', 'ws': 'USD', 'sm': 'USD', 'st': 'USD',
    'sn': 'USD', 'sc': 'USD', 'sl': 'USD', 'sb': 'USD', 'so': 'USD', 'ss': 'USD',
    'sd': 'USD', 'sz': 'USD', 'tj': 'USD', 'tg': 'USD', 'to': 'USD', 'ua': 'USD',
    'tt': 'USD', 'tn': 'USD', 'tm': 'USD', 'tv': 'USD', 'ug': 'USD', 'uy': 'USD',
    'uz': 'USD', 'vu': 'USD', 've': 'USD', 'wf': 'USD', 'ye': 'USD'
}

/** A dictionary mapping two-letter country codes to their names. */
export const countryData: { [key: string]: string } = {
  al: 'Albania',
  dz: 'Algeria',
  ao: 'Angola',
  ar: 'Argentina',
  am: 'Armenia',
  au: 'Australia',
  at: 'Austria',
  az: 'Azerbaijan',
  bs: 'Bahamas',
  bh: 'Bahrain',
  bd: 'Bangladesh',
  by: 'Belarus',
  be: 'Belgium',
  bz: 'Belize',
  bt: 'Bhutan',
  bw: 'Botswana',
  br: 'Brazil',
  bg: 'Bulgaria',
  kh: 'Cambodia',
  cm: 'Cameroon',
  ca: 'Canada',
  cv: 'Cape Verde',
  cl: 'Chile',
  cn: 'China',
  co: 'Colombia',
  cr: 'Costa Rica',
  ci: "Côte d'Ivoire",
  hr: 'Croatia',
  cu: 'Cuba',
  cy: 'Cyprus',
  cz: 'Czech Republic',
  dk: 'Denmark',
  do: 'Dominican Republic',
  ec: 'Ecuador',
  eg: 'Egypt',
  sv: 'El Salvador',
  ee: 'Estonia',
  sz: 'Eswatini',
  fo: 'Faroe Islands',
  fj: 'Fiji',
  fi: 'Finland',
  fr: 'France',
  pf: 'French Polynesia',
  ge: 'Georgia',
  de: 'Germany',
  gh: 'Ghana',
  gi: 'Gibraltar',
  gr: 'Greece',
  gl: 'Greenland',
  gt: 'Guatemala',
  ht: 'Haiti',
  hn: 'Honduras',
  hk: 'Hong Kong',
  hu: 'Hungary',
  is: 'Iceland',
  in: 'India',
  id: 'Indonesia',
  ir: 'Iran',
  iq: 'Iraq',
  ie: 'Ireland',
  il: 'Israel',
  it: 'Italy',
  jm: 'Jamaica',
  jp: 'Japan',
  jo: 'Jordan',
  kz: 'Kazakhstan',
  ke: 'Kenya',
  ki: 'Kiribati',
  kr: 'Korea, Republic of',
  xk: 'Kosovo',
  kw: 'Kuwait',
  la: "Lao People's Democratic Republic",
  lv: 'Latvia',
  lb: 'Lebanon',
  ls: 'Lesotho',
  li: 'Liechtenstein',
  lt: 'Lithuania',
  lu: 'Luxembourg',
  my: 'Malaysia',
  mv: 'Maldives',
  mx: 'Mexico',
  md: 'Moldova, Republic of',
  mc: 'Monaco',
  mn: 'Mongolia',
  me: 'Montenegro',
  ma: 'Morocco',
  mz: 'Mozambique',
  mm: 'Myanmar',
  na: 'Namibia',
  nr: 'Nauru',
  np: 'Nepal',
  nl: 'Netherlands',
  nc: 'New Caledonia',
  nz: 'New Zealand',
  ni: 'Nicaragua',
  ng: 'Nigeria',
  mk: 'North Macedonia',
  no: 'Norway',
  om: 'Oman',
  pk: 'Pakistan',
  ps: 'Palestine',
  pa: 'Panama',
  pg: 'Papua New Guinea',
  pe: 'Peru',
  ph: 'Philippines',
  pl: 'Poland',
  pt: 'Portugal',
  qa: 'Qatar',
  ro: 'Romania',
  ru: 'Russia',
  ws: 'Samoa',
  sm: 'San Marino',
  st: 'São Tomé and Príncipe',
  sa: 'Saudi Arabia',
  sn: 'Senegal',
  rs: 'Serbia',
  sg: 'Singapore',
  sk: 'Slovakia',
  si: 'Slovenia',
  sb: 'Solomon Islands',
  za: 'South Africa',
  es: 'Spain',
  sd: 'Sudan',
  se: 'Sweden',
  ch: 'Switzerland',
  sy: 'Syria',
  tw: 'Taiwan',
  tz: 'Tanzania, United Republic of',
  th: 'Thailand',
  tl: 'Timor-Leste',
  tk: 'Tokelau',
  to: 'Tonga',
  tt: 'Trinidad and Tobago',
  tr: 'Turkey',
  ug: 'Uganda',
  ua: 'Ukraine',
  ae: 'United Arab Emirates',
  gb: 'United Kingdom',
  us: 'United States',
  uy: 'Uruguay',
  vu: 'Vanuatu',
  va: 'Vatican City',
  ve: 'Venezuela',
  vn: 'Vietnam',
  wf: 'Wallis and Futuna',
  mw: 'Malawi',
  zm: 'Zambia',
  zw: 'Zimbabwe',
};
